// SPDX-License-Identifier: GPL-3.0-or-later

plugins {
    id('com.android.test')
}

android {
    namespace = 'io.github.sysadmindoc.appmanagerng.benchmark'
    compileSdk = compile_sdk
    targetProjectPath = ':app'

    signingConfigs {
        debug {
            def appDevKeystore = file('../app/dev_keystore.jks')
            if (appDevKeystore.exists()) {
                storeFile appDevKeystore
                storePassword 'kJCp!Bda#PBdN2RLK%yMK@hatq&69E'
                keyPassword 'kJCp!Bda#PBdN2RLK%yMK@hatq&69E'
                keyAlias 'key0'
            }
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.debug
        }
    }

    defaultConfig {
        minSdk = 23
        targetSdk = target_sdk
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
        testInstrumentationRunnerArguments['androidx.benchmark.suppressErrors'] =
                'ACTIVITY-MISSING,DEBUGGABLE,EMULATOR'
        missingDimensionStrategy 'distribution', 'floss'
    }

    compileOptions {
        encoding = 'UTF-8'
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':libcore:compat')
    implementation "androidx.collection:collection:1.5.0"
    implementation "androidx.benchmark:benchmark-junit4:${benchmark_version}"
    implementation "androidx.benchmark:benchmark-macro-junit4:${benchmark_version}"
    implementation "androidx.test:runner:1.6.2"
    implementation "androidx.test.ext:junit:1.2.1"
    implementation "androidx.test.uiautomator:uiautomator:${uiautomator_version}"
    implementation "junit:junit:${junit_version}"
}
