// SPDX-License-Identifier: GPL-3.0-or-later

package io.github.muntashirakon.AppManager.details.profile;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.WorkerThread;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;

import io.github.muntashirakon.AppManager.runner.Runner;

/**
 * Privileged-runner glue for the T20-A Perfetto trace export and T20-B
 * simpleperf CPU profile capture App Details actions.
 *
 * <p>Both captures share the same shape: build a validated argv from the
 * JVM-tested command builders, run it through {@link Runner} (root / Shizuku /
 * ADB), and report where the artifact landed. The Perfetto config is piped via
 * {@code stdin} ({@code perfetto -c - --txt}) so no temp file has to be made
 * readable across the root/shell uid boundary.
 *
 * <p>Capture is bounded by the requested duration, so the privileged process
 * self-terminates; true mid-capture cancellation (killing the child) is a
 * follow-up.
 */
public final class AppProfileCapture {

    private AppProfileCapture() {
    }

    public static final class Result {
        public final boolean success;
        @Nullable
        public final String outputPath;
        @Nullable
        public final String error;

        private Result(boolean success, @Nullable String outputPath, @Nullable String error) {
            this.success = success;
            this.outputPath = outputPath;
            this.error = error;
        }

        @NonNull
        static Result ok(@NonNull String outputPath) {
            return new Result(true, outputPath, null);
        }

        @NonNull
        static Result fail(@Nullable String error) {
            return new Result(false, null, error);
        }
    }

    /**
     * Capture a Perfetto system trace for {@code packageName}, writing the
     * trace to {@code outputPath}. The text-proto config is generated by
     * {@link PerfettoTraceConfigBuilder} (duration clamped) and fed to
     * {@code perfetto} on stdin.
     */
    @WorkerThread
    @NonNull
    public static Result capturePerfettoTrace(@NonNull String packageName, long durationMillis,
                                              @NonNull String outputPath) {
        String[] argv;
        String proto;
        try {
            long clamped = PerfettoTraceConfigBuilder.clampDuration(durationMillis);
            proto = PerfettoTraceConfigBuilder.buildTextProto(packageName, clamped);
            argv = PerfettoCommandBuilder.buildRecord("-", outputPath);
            PrivilegedRunnerArgValidator.validateArgv(argv);
        } catch (IllegalArgumentException e) {
            return Result.fail(e.getMessage());
        }
        try {
            Runner.Result result = Runner.runCommand(argv,
                    new ByteArrayInputStream(proto.getBytes(StandardCharsets.UTF_8)));
            if (result != null && result.isSuccessful()) {
                return Result.ok(outputPath);
            }
            return Result.fail(describeFailure(result));
        } catch (Throwable t) {
            return Result.fail(t.getMessage());
        }
    }

    /**
     * Capture a simpleperf CPU profile for {@code packageName} over
     * {@code durationSeconds} sampling {@code event}, writing the raw
     * {@code perf.data} to {@code outputPath}.
     */
    @WorkerThread
    @NonNull
    public static Result captureCpuProfile(@NonNull String packageName, int durationSeconds,
                                           @Nullable String event, @NonNull String outputPath) {
        String[] argv;
        try {
            argv = CpuProfileCommandBuilder.build(packageName, durationSeconds, event, outputPath);
            PrivilegedRunnerArgValidator.validateArgv(argv);
        } catch (IllegalArgumentException e) {
            return Result.fail(e.getMessage());
        }
        try {
            Runner.Result result = Runner.runCommand(argv);
            if (result != null && result.isSuccessful()) {
                return Result.ok(outputPath);
            }
            return Result.fail(describeFailure(result));
        } catch (Throwable t) {
            return Result.fail(t.getMessage());
        }
    }

    @Nullable
    private static String describeFailure(@Nullable Runner.Result result) {
        if (result == null) {
            return null;
        }
        List<String> stderr = result.getStderr();
        if (stderr != null && !stderr.isEmpty()) {
            String joined = android.text.TextUtils.join("\n", stderr).trim();
            if (!joined.isEmpty()) {
                return joined;
            }
        }
        return "exit code " + result.getExitCode();
    }
}
